name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: aarch64-apple-darwin, os: macos-14 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4
      - name: install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - uses: Swatinem/rust-cache@v2

      - name: build
        run: cargo build --target ${{ matrix.platform.target }}

      - name: build tests
        shell: bash
        run: cargo test --no-run --verbose --target ${{ matrix.platform.target }}

      - name: run tests
        run: cargo test --verbose --target ${{ matrix.platform.target }}
